##############################################
#     Make file of SONYIMX188 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/media/video/hik3/capture/sonyimx188/
#EXTRA_CFLAGS += -fno-pic
obj-$(CONFIG_HIK3_CAMERA_SONYIMX188) += sonyimx188.o

#################### END #####################
