#
# Makefile for sensor chip drivers.
#
obj-$(CONFIG_K3V2_CPU_TEMP_SENSOR)	+= k3v2_temp_sensor.o
obj-$(CONFIG_K3V2_AP_SENSOR)	+= ap_temp_sensor.o
obj-$(CONFIG_K3V2_SIM_SENSOR)	+= sim_temp_sensor.o
obj-$(CONFIG_SENSORS_NCT203)	+= nct203_temp_sensor.o
obj-$(CONFIG_THERMAL_CONFIG)	+= show_product_thermal_conf.o

obj-y	+= k3v2_temperature.o
