##############################################
#     Make file of OV5642 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/media/video/hik3/capture/ov5642
EXTRA_CFLAGS += -fno-pic 
#obj-$(CONFIG_HIK3_CAMERA_OV5642) += ov5642.o
obj-m += ov5642.o

#################### END #####################
