##############################################
#     Make file of s5k5cag camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/media/video/hik3/capture/s5k5cag
EXTRA_CFLAGS += -fno-pic
obj-$(CONFIG_HIK3_CAMERA_S5K5CAG) += s5k5cag.o

#################### END #####################
