##############################################
#     Make file of SONYIMX105 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/media/video/hik3/capture/sonyimx105/
#EXTRA_CFLAGS += -fno-pic 
obj-$(CONFIG_HIK3_CAMERA_SONYIMX105) += sonyimx105.o

#################### END #####################
