##############################################
#     Make file of S5K4E1GA_FOXCONN camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/media/video/hik3/capture/s5k4e1ga_foxconn/
#EXTRA_CFLAGS += -fno-pic
obj-$(CONFIG_HIK3_CAMERA_S5K4E1GA_FOXCONN) += s5k4e1ga_foxconn.o

#################### END #####################
