##############################################
#     Make file of OV8830 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/media/video/hik3/capture/ov8830/
EXTRA_CFLAGS += -fno-pic 
obj-$(CONFIG_HIK3_CAMERA_OV8830) += ov8830.o
#obj-m += ov8830.o

#################### END #####################
