#
# Makefile for the linux kernel.
#
#gcc -I /arch/arm/mach-k3v2/hiadc/include/linux

HADCOFILES =  hi6421-adc_os.o\
     hi6421-adc_driver.o\
     k3-adc-hwmon.o
          
obj-y += hiadc.o
hiadc-objs += $(HADCOFILES)

# obj-y +=  hiadc.o

