##############################################
#     Make file of mt9m114 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/media/video/hik3/capture/mt9m114
EXTRA_CFLAGS += -fno-pic 
obj-$(CONFIG_HIK3_CAMERA_MT9M114) += mt9m114.o
#obj-m += mt9m114.o

#################### END #####################
