##############################################
#     Make file of SONYIMX105 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/media/video/hik3/capture/sonyimx134/
#EXTRA_CFLAGS += -fno-pic 
ccflags-y += -DIMX134_OTP
obj-y += imx134_tune.o
obj-y += sonyimx134.o

#################### END #####################
