##############################################
#     Make file of S5K3H2YX_FOXCONN camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/media/video/hik3/capture/s5k3h2yx_foxconn/
#EXTRA_CFLAGS += -fno-pic 
obj-$(CONFIG_HIK3_CAMERA_S5K3H2YX_FOXCONN) += s5k3h2yx_foxconn.o

#################### END #####################
