##############################################
#     Make file of HI542 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/media/video/hik3/capture/hi542/
#EXTRA_CFLAGS += -fno-pic
obj-$(CONFIG_HIK3_CAMERA_HI542) += hi542.o

#################### END #####################
