##############################################
#     Make file of SONYIMX091 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/media/video/hik3/capture/sonyimx091/
#EXTRA_CFLAGS += -fno-pic
obj-$(CONFIG_HIK3_CAMERA_SONYIMX091) += sonyimx091.o

#################### END #####################
