##############################################
#     Make file of SONYIMX135 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/media/video/hik3/capture/sonyimx135/
#EXTRA_CFLAGS += -fno-pic
obj-$(CONFIG_HIK3_CAMERA_SONYIMX135) += sonyimx135.o

#################### END #####################
