/* This file is auto-generated by tool, please don't manully modify it.*/

#include <hsad/config_boardids.h>

#include "hw_U9800DVBL_configs.c"
#include "hw_U9700GVB_configs.c"
#include "hw_UEDGE10LAYER_configs.c"
#include "hw_CEDGED_configs.c"
#include "hw_CEDGEDV3_configs.c"
#include "hw_U9900VGB_configs.c"
#include "hw_C9800D_configs.c"
#include "hw_vdcs_k3oem_configs.c"
#include "hw_vacsddr3_k3oem_configs.c"
#include "hw_UEDGE_configs.c"
#include "hw_vacs_k3oem_configs.c"
#include "hw_TEDGE_configs.c"
#include "hw_apu1ve_k3oem_configs.c"
#include "hw_vccs_k3oem_configs.c"
#include "hw_TEDGEV3_configs.c"
#include "hw_C9800DVB_configs.c"
#include "hw_U9900LEUVB_configs.c"
#include "hw_U9700LVB_configs.c"
#include "hw_UEDGE_G_configs.c"
#include "hw_T9800LVA_configs.c"
#include "hw_U9900VBV4_configs.c"
#include "hw_U9701L_VB_configs.c"
#include "hw_UEDGEV3_configs.c"
#include "hw_T9800L_configs.c"
#include "hw_T9800LVBL_configs.c"
#include "hw_T9900_configs.c"
#include "hw_U9700LVA_configs.c"
#include "hw_U9900_configs.c"
#include "hw_U9900LAUVB_configs.c"
#include "hw_T9800LVAT_configs.c"
#include "hw_C9800DVA_configs.c"
#include "hw_U9800DNV1_configs.c"
#include "hw_UEDGEVDF_configs.c"
#include "hw_T9800LVB_configs.c"
#include "hw_U9900LLAVB_configs.c"
#include "hw_C9800DVAT_configs.c"
#include "hw_U9900L_configs.c"
#include "hw_U9701L_TEST_VB_configs.c"
#include "hw_U9700GVA_configs.c"
#include "hw_C9800DVBL_configs.c"
#include "hw_U9701L_VA_configs.c"
#include "hw_U9900VB_configs.c"
#include "hw_U9700GVC_configs.c"
#include "hw_U9701G_VA_configs.c"
extern struct board_id_general_struct config_power_U9800DVBL;
extern struct board_id_general_struct config_power_U9700GVB;
extern struct board_id_general_struct config_power_UEDGE10LAYER;
extern struct board_id_general_struct config_power_CEDGED;
extern struct board_id_general_struct config_power_CEDGEDV3;
extern struct board_id_general_struct config_power_U9900VGB;
extern struct board_id_general_struct config_power_C9800D;
extern struct board_id_general_struct config_power_vdcs_k3oem;
extern struct board_id_general_struct config_power_vacsddr3_k3oem;
extern struct board_id_general_struct config_power_UEDGE;
extern struct board_id_general_struct config_power_vacs_k3oem;
extern struct board_id_general_struct config_power_TEDGE;
extern struct board_id_general_struct config_power_apu1ve_k3oem;
extern struct board_id_general_struct config_power_vccs_k3oem;
extern struct board_id_general_struct config_power_TEDGEV3;
extern struct board_id_general_struct config_power_C9800DVB;
extern struct board_id_general_struct config_power_U9900LEUVB;
extern struct board_id_general_struct config_power_U9700LVB;
extern struct board_id_general_struct config_power_UEDGE_G;
extern struct board_id_general_struct config_power_T9800LVA;
extern struct board_id_general_struct config_power_U9900VBV4;
extern struct board_id_general_struct config_power_U9701L_VB;
extern struct board_id_general_struct config_power_UEDGEV3;
extern struct board_id_general_struct config_power_T9800L;
extern struct board_id_general_struct config_power_T9800LVBL;
extern struct board_id_general_struct config_power_T9900;
extern struct board_id_general_struct config_power_U9700LVA;
extern struct board_id_general_struct config_power_U9900;
extern struct board_id_general_struct config_power_U9900LAUVB;
extern struct board_id_general_struct config_power_T9800LVAT;
extern struct board_id_general_struct config_power_C9800DVA;
extern struct board_id_general_struct config_power_U9800DNV1;
extern struct board_id_general_struct config_power_UEDGEVDF;
extern struct board_id_general_struct config_power_T9800LVB;
extern struct board_id_general_struct config_power_U9900LLAVB;
extern struct board_id_general_struct config_power_C9800DVAT;
extern struct board_id_general_struct config_power_U9900L;
extern struct board_id_general_struct config_power_U9701L_TEST_VB;
extern struct board_id_general_struct config_power_U9700GVA;
extern struct board_id_general_struct config_power_C9800DVBL;
extern struct board_id_general_struct config_power_U9701L_VA;
extern struct board_id_general_struct config_power_U9900VB;
extern struct board_id_general_struct config_power_U9700GVC;
extern struct board_id_general_struct config_power_U9701G_VA;

/*gpio perl producted data*/
#ifdef CONFIG_HUAWEI_GPIO_UNITE
extern struct board_id_general_struct config_gpio_U9800DVBL;
extern struct board_id_general_struct config_pm_gpio_U9800DVBL;
extern struct board_id_general_struct config_gpio_U9700GVB;
extern struct board_id_general_struct config_pm_gpio_U9700GVB;
extern struct board_id_general_struct config_gpio_UEDGE10LAYER;
extern struct board_id_general_struct config_pm_gpio_UEDGE10LAYER;
extern struct board_id_general_struct config_gpio_CEDGED;
extern struct board_id_general_struct config_pm_gpio_CEDGED;
extern struct board_id_general_struct config_gpio_CEDGEDV3;
extern struct board_id_general_struct config_pm_gpio_CEDGEDV3;
extern struct board_id_general_struct config_gpio_U9900VGB;
extern struct board_id_general_struct config_pm_gpio_U9900VGB;
extern struct board_id_general_struct config_gpio_C9800D;
extern struct board_id_general_struct config_pm_gpio_C9800D;
extern struct board_id_general_struct config_gpio_vdcs_k3oem;
extern struct board_id_general_struct config_pm_gpio_vdcs_k3oem;
extern struct board_id_general_struct config_gpio_vacsddr3_k3oem;
extern struct board_id_general_struct config_pm_gpio_vacsddr3_k3oem;
extern struct board_id_general_struct config_gpio_UEDGE;
extern struct board_id_general_struct config_pm_gpio_UEDGE;
extern struct board_id_general_struct config_gpio_vacs_k3oem;
extern struct board_id_general_struct config_pm_gpio_vacs_k3oem;
extern struct board_id_general_struct config_gpio_TEDGE;
extern struct board_id_general_struct config_pm_gpio_TEDGE;
extern struct board_id_general_struct config_gpio_apu1ve_k3oem;
extern struct board_id_general_struct config_pm_gpio_apu1ve_k3oem;
extern struct board_id_general_struct config_gpio_vccs_k3oem;
extern struct board_id_general_struct config_pm_gpio_vccs_k3oem;
extern struct board_id_general_struct config_gpio_TEDGEV3;
extern struct board_id_general_struct config_pm_gpio_TEDGEV3;
extern struct board_id_general_struct config_gpio_C9800DVB;
extern struct board_id_general_struct config_pm_gpio_C9800DVB;
extern struct board_id_general_struct config_gpio_U9900LEUVB;
extern struct board_id_general_struct config_pm_gpio_U9900LEUVB;
extern struct board_id_general_struct config_gpio_U9700LVB;
extern struct board_id_general_struct config_pm_gpio_U9700LVB;
extern struct board_id_general_struct config_gpio_UEDGE_G;
extern struct board_id_general_struct config_pm_gpio_UEDGE_G;
extern struct board_id_general_struct config_gpio_T9800LVA;
extern struct board_id_general_struct config_pm_gpio_T9800LVA;
extern struct board_id_general_struct config_gpio_U9900VBV4;
extern struct board_id_general_struct config_pm_gpio_U9900VBV4;
extern struct board_id_general_struct config_gpio_U9701L_VB;
extern struct board_id_general_struct config_pm_gpio_U9701L_VB;
extern struct board_id_general_struct config_gpio_UEDGEV3;
extern struct board_id_general_struct config_pm_gpio_UEDGEV3;
extern struct board_id_general_struct config_gpio_T9800L;
extern struct board_id_general_struct config_pm_gpio_T9800L;
extern struct board_id_general_struct config_gpio_T9800LVBL;
extern struct board_id_general_struct config_pm_gpio_T9800LVBL;
extern struct board_id_general_struct config_gpio_T9900;
extern struct board_id_general_struct config_pm_gpio_T9900;
extern struct board_id_general_struct config_gpio_U9700LVA;
extern struct board_id_general_struct config_pm_gpio_U9700LVA;
extern struct board_id_general_struct config_gpio_U9900;
extern struct board_id_general_struct config_pm_gpio_U9900;
extern struct board_id_general_struct config_gpio_U9900LAUVB;
extern struct board_id_general_struct config_pm_gpio_U9900LAUVB;
extern struct board_id_general_struct config_gpio_T9800LVAT;
extern struct board_id_general_struct config_pm_gpio_T9800LVAT;
extern struct board_id_general_struct config_gpio_C9800DVA;
extern struct board_id_general_struct config_pm_gpio_C9800DVA;
extern struct board_id_general_struct config_gpio_U9800DNV1;
extern struct board_id_general_struct config_pm_gpio_U9800DNV1;
extern struct board_id_general_struct config_gpio_UEDGEVDF;
extern struct board_id_general_struct config_pm_gpio_UEDGEVDF;
extern struct board_id_general_struct config_gpio_T9800LVB;
extern struct board_id_general_struct config_pm_gpio_T9800LVB;
extern struct board_id_general_struct config_gpio_U9900LLAVB;
extern struct board_id_general_struct config_pm_gpio_U9900LLAVB;
extern struct board_id_general_struct config_gpio_C9800DVAT;
extern struct board_id_general_struct config_pm_gpio_C9800DVAT;
extern struct board_id_general_struct config_gpio_U9900L;
extern struct board_id_general_struct config_pm_gpio_U9900L;
extern struct board_id_general_struct config_gpio_U9701L_TEST_VB;
extern struct board_id_general_struct config_pm_gpio_U9701L_TEST_VB;
extern struct board_id_general_struct config_gpio_U9700GVA;
extern struct board_id_general_struct config_pm_gpio_U9700GVA;
extern struct board_id_general_struct config_gpio_C9800DVBL;
extern struct board_id_general_struct config_pm_gpio_C9800DVBL;
extern struct board_id_general_struct config_gpio_U9701L_VA;
extern struct board_id_general_struct config_pm_gpio_U9701L_VA;
extern struct board_id_general_struct config_gpio_U9900VB;
extern struct board_id_general_struct config_pm_gpio_U9900VB;
extern struct board_id_general_struct config_gpio_U9700GVC;
extern struct board_id_general_struct config_pm_gpio_U9700GVC;
extern struct board_id_general_struct config_gpio_U9701G_VA;
extern struct board_id_general_struct config_pm_gpio_U9701G_VA;
#endif

/*total table*/
struct board_id_general_struct  *hw_ver_total_configs[] =
{
#ifdef CONFIG_HUAWEI_GPIO_UNITE
    &config_gpio_U9800DVBL, //gpio
    &config_gpio_U9700GVB, //gpio
    &config_gpio_UEDGE10LAYER, //gpio
    &config_gpio_CEDGED, //gpio
    &config_gpio_CEDGEDV3, //gpio
    &config_gpio_U9900VGB, //gpio
    &config_gpio_C9800D, //gpio
    &config_gpio_vdcs_k3oem, //gpio
    &config_gpio_vacsddr3_k3oem, //gpio
    &config_gpio_UEDGE, //gpio
    &config_gpio_vacs_k3oem, //gpio
    &config_gpio_TEDGE, //gpio
    &config_gpio_apu1ve_k3oem, //gpio
    &config_gpio_vccs_k3oem, //gpio
    &config_gpio_TEDGEV3, //gpio
    &config_gpio_C9800DVB, //gpio
    &config_gpio_U9900LEUVB, //gpio
    &config_gpio_U9700LVB, //gpio
    &config_gpio_UEDGE_G, //gpio
    &config_gpio_T9800LVA, //gpio
    &config_gpio_U9900VBV4, //gpio
    &config_gpio_U9701L_VB, //gpio
    &config_gpio_UEDGEV3, //gpio
    &config_gpio_T9800L, //gpio
    &config_gpio_T9800LVBL, //gpio
    &config_gpio_T9900, //gpio
    &config_gpio_U9700LVA, //gpio
    &config_gpio_U9900, //gpio
    &config_gpio_U9900LAUVB, //gpio
    &config_gpio_T9800LVAT, //gpio
    &config_gpio_C9800DVA, //gpio
    &config_gpio_U9800DNV1, //gpio
    &config_gpio_UEDGEVDF, //gpio
    &config_gpio_T9800LVB, //gpio
    &config_gpio_U9900LLAVB, //gpio
    &config_gpio_C9800DVAT, //gpio
    &config_gpio_U9900L, //gpio
    &config_gpio_U9701L_TEST_VB, //gpio
    &config_gpio_U9700GVA, //gpio
    &config_gpio_C9800DVBL, //gpio
    &config_gpio_U9701L_VA, //gpio
    &config_gpio_U9900VB, //gpio
    &config_gpio_U9700GVC, //gpio
    &config_gpio_U9701G_VA, //gpio
#endif
#ifdef CONFIG_HUAWEI_GPIO_UNITE
    &config_pm_gpio_U9800DVBL, //pm gpio
    &config_pm_gpio_U9700GVB, //pm gpio
    &config_pm_gpio_UEDGE10LAYER, //pm gpio
    &config_pm_gpio_CEDGED, //pm gpio
    &config_pm_gpio_CEDGEDV3, //pm gpio
    &config_pm_gpio_U9900VGB, //pm gpio
    &config_pm_gpio_C9800D, //pm gpio
    &config_pm_gpio_vdcs_k3oem, //pm gpio
    &config_pm_gpio_vacsddr3_k3oem, //pm gpio
    &config_pm_gpio_UEDGE, //pm gpio
    &config_pm_gpio_vacs_k3oem, //pm gpio
    &config_pm_gpio_TEDGE, //pm gpio
    &config_pm_gpio_apu1ve_k3oem, //pm gpio
    &config_pm_gpio_vccs_k3oem, //pm gpio
    &config_pm_gpio_TEDGEV3, //pm gpio
    &config_pm_gpio_C9800DVB, //pm gpio
    &config_pm_gpio_U9900LEUVB, //pm gpio
    &config_pm_gpio_U9700LVB, //pm gpio
    &config_pm_gpio_UEDGE_G, //pm gpio
    &config_pm_gpio_T9800LVA, //pm gpio
    &config_pm_gpio_U9900VBV4, //pm gpio
    &config_pm_gpio_U9701L_VB, //pm gpio
    &config_pm_gpio_UEDGEV3, //pm gpio
    &config_pm_gpio_T9800L, //pm gpio
    &config_pm_gpio_T9800LVBL, //pm gpio
    &config_pm_gpio_T9900, //pm gpio
    &config_pm_gpio_U9700LVA, //pm gpio
    &config_pm_gpio_U9900, //pm gpio
    &config_pm_gpio_U9900LAUVB, //pm gpio
    &config_pm_gpio_T9800LVAT, //pm gpio
    &config_pm_gpio_C9800DVA, //pm gpio
    &config_pm_gpio_U9800DNV1, //pm gpio
    &config_pm_gpio_UEDGEVDF, //pm gpio
    &config_pm_gpio_T9800LVB, //pm gpio
    &config_pm_gpio_U9900LLAVB, //pm gpio
    &config_pm_gpio_C9800DVAT, //pm gpio
    &config_pm_gpio_U9900L, //pm gpio
    &config_pm_gpio_U9701L_TEST_VB, //pm gpio
    &config_pm_gpio_U9700GVA, //pm gpio
    &config_pm_gpio_C9800DVBL, //pm gpio
    &config_pm_gpio_U9701L_VA, //pm gpio
    &config_pm_gpio_U9900VB, //pm gpio
    &config_pm_gpio_U9700GVC, //pm gpio
    &config_pm_gpio_U9701G_VA, //pm gpio
#endif
    &config_common_U9800DVBL, //common xml
    &config_common_U9700GVB, //common xml
    &config_common_UEDGE10LAYER, //common xml
    &config_common_CEDGED, //common xml
    &config_common_CEDGEDV3, //common xml
    &config_common_U9900VGB, //common xml
    &config_common_C9800D, //common xml
    &config_common_vdcs_k3oem, //common xml
    &config_common_vacsddr3_k3oem, //common xml
    &config_common_UEDGE, //common xml
    &config_common_vacs_k3oem, //common xml
    &config_common_TEDGE, //common xml
    &config_common_apu1ve_k3oem, //common xml
    &config_common_vccs_k3oem, //common xml
    &config_common_TEDGEV3, //common xml
    &config_common_C9800DVB, //common xml
    &config_common_U9900LEUVB, //common xml
    &config_common_U9700LVB, //common xml
    &config_common_UEDGE_G, //common xml
    &config_common_T9800LVA, //common xml
    &config_common_U9900VBV4, //common xml
    &config_common_U9701L_VB, //common xml
    &config_common_UEDGEV3, //common xml
    &config_common_T9800L, //common xml
    &config_common_T9800LVBL, //common xml
    &config_common_T9900, //common xml
    &config_common_U9700LVA, //common xml
    &config_common_U9900, //common xml
    &config_common_U9900LAUVB, //common xml
    &config_common_T9800LVAT, //common xml
    &config_common_C9800DVA, //common xml
    &config_common_U9800DNV1, //common xml
    &config_common_UEDGEVDF, //common xml
    &config_common_T9800LVB, //common xml
    &config_common_U9900LLAVB, //common xml
    &config_common_C9800DVAT, //common xml
    &config_common_U9900L, //common xml
    &config_common_U9701L_TEST_VB, //common xml
    &config_common_U9700GVA, //common xml
    &config_common_C9800DVBL, //common xml
    &config_common_U9701L_VA, //common xml
    &config_common_U9900VB, //common xml
    &config_common_U9700GVC, //common xml
    &config_common_U9701G_VA, //common xml
};
